<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-03T07:06:12 IST" name="Default suite" finished-at="2022-12-03T07:07:04 IST" duration-ms="52323">
    <groups>
    </groups>
    <test started-at="2022-12-03T07:06:12 IST" name="Default test" finished-at="2022-12-03T07:07:04 IST" duration-ms="52323">
      <class name="DDF_POM_TestNG_Base_Utility_Class.GitHubTest">
        <test-method is-config="true" signature="browserOpen()[pri:0, instance:DDF_POM_TestNG_Base_Utility_Class.GitHubTest@708f5957]" started-at="2022-12-03T07:06:12 IST" name="browserOpen" finished-at="2022-12-03T07:06:34 IST" duration-ms="21915" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserOpen -->
        <test-method is-config="true" signature="login()[pri:0, instance:DDF_POM_TestNG_Base_Utility_Class.GitHubTest@708f5957]" started-at="2022-12-03T07:06:34 IST" name="login" finished-at="2022-12-03T07:06:54 IST" duration-ms="20768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="test()[pri:0, instance:DDF_POM_TestNG_Base_Utility_Class.GitHubTest@708f5957]" started-at="2022-12-03T07:06:54 IST" name="test" finished-at="2022-12-03T07:06:55 IST" duration-ms="784" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[act & exp result is different expected [Yojana7222] but found [Yojana722]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: act & exp result is different expected [Yojana7222] but found [Yojana722]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at DDF_POM_TestNG_Base_Utility_Class.GitHubTest.test(GitHubTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="logOut(org.testng.ITestResult)[pri:0, instance:DDF_POM_TestNG_Base_Utility_Class.GitHubTest@708f5957]" started-at="2022-12-03T07:06:55 IST" name="logOut" finished-at="2022-12-03T07:07:01 IST" duration-ms="5744" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=FAILURE method=GitHubTest.test()[pri:0, instance:DDF_POM_TestNG_Base_Utility_Class.GitHubTest@708f5957] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:DDF_POM_TestNG_Base_Utility_Class.GitHubTest@708f5957]" started-at="2022-12-03T07:07:01 IST" name="closeBrowser" finished-at="2022-12-03T07:07:04 IST" duration-ms="2982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- DDF_POM_TestNG_Base_Utility_Class.GitHubTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
